#!/usr/bin/env python3
# Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: MIT-0

"""Local fixture for the query service, assembled from the production artefacts so the stack holds the
production dataset (every product file in data/products/).

Writes, under generated/:
  sql/<n>-<database>.sql one PostgreSQL database per source (fr_plm, de_plm, uk_plm, es_plm, atelier_core), each
                         created and then migrated with the service's own Flyway migrations in Flyway's order: the
                         versioned V*.sql in version order, then the repeatable R__*.sql seed
                         (modules/plm-services/<module>/src/main/resources/db/migration/), which
                         data/generate.py derives from data/products/*.json. One file per database, numbered in the
                         order PostgreSQL's entrypoint runs them; each stays under the 500 KB a public sample may hold
  ontop/<source>.r2rml.ttl, <source>-db-metadata.json
                         the mapping each Ontop endpoint runs and the schema the query service reformulates
                         against: copies of modules/ontop/mappings and modules/ontop/metadata
  ontop/<source>.properties
                         the endpoint's JDBC settings and the query log of the production entrypoint
  links.ttl, fileindex.ttl, labels.ttl, options.ttl
                         the link-store graphs: copies of data/links.ttl, data/fileindex.ttl (each part's
                         atelier:cadFile and, on a supplier-built part, its atelier:builtBy), data/labels.ttl
                         (each item's native and English names, the glossary) and data/options.ttl (the variant
                         groups, their options and what exists only under an option)

Standard library only: python3 generate.py
"""
import pathlib
import re
import shutil

HERE = pathlib.Path(__file__).resolve().parent
ROOT = HERE.parents[2]
OUT = HERE / "generated"
SERVICES = ROOT / "modules" / "plm-services"
ONTOP = ROOT / "modules" / "ontop"
DATA = ROOT / "data"

# Source code -> (service module, database).
SOURCES = {"fr": ("plm-fr", "fr_plm"), "de": ("plm-de", "de_plm"), "uk": ("plm-uk", "uk_plm"), "es": ("plm-es", "es_plm"),
           "core": ("atelier-core", "atelier_core")}
VERSION = re.compile(r"^V(\d+)__")
# Licence header of every file written here (the tree-wide SPDX header); the copied files carry their sources'.
LICENCE = ("Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.", "SPDX-License-Identifier: MIT-0")

# Same query log as modules/ontop/src/entrypoint.sh: one JSON line per request with reformulationCacheHit.
QUERY_LOG = """ontop.queryLogging=true
ontop.queryLogging.includeSparqlQuery=false
ontop.queryLogging.includeReformulatedQuery=false
ontop.queryLogging.includeTables=true
"""


def migrations(module):
    """The module's Flyway migrations as Flyway applies them: versioned in version order, then repeatable by name."""
    folder = SERVICES / module / "src" / "main" / "resources" / "db" / "migration"
    versioned = sorted((f for f in folder.iterdir() if VERSION.match(f.name)), key=lambda f: int(VERSION.match(f.name).group(1)))
    return versioned + sorted(f for f in folder.iterdir() if f.name.startswith("R__") and f.suffix == ".sql")


def seed(module, database):
    """The SQL that creates one source's database and migrates it as Flyway does."""
    lines = [*(f"-- {line}" for line in LICENCE), "",
             f"-- Generated by fixtures/generate.py from {module}'s Flyway migrations; do not edit by hand.",
             f"CREATE DATABASE {database};", f"\\connect {database}"]
    for migration in migrations(module):
        lines += [f"-- {module}/{migration.name}", migration.read_text(encoding="utf-8").rstrip()]
    return "\n".join(lines) + "\n"


def properties(database):
    return ("".join(f"# {line}\n" for line in LICENCE) + "\n"
            f"jdbc.url=jdbc:postgresql://pg:5432/{database}\njdbc.user=postgres\n"
            "# pragma: allowlist nextline secret -- the local fixture database password, not a credential\n"
            "jdbc.password=fixture\njdbc.driver=org.postgresql.Driver\n" + QUERY_LOG)


def main():
    (OUT / "sql").mkdir(parents=True, exist_ok=True)
    (OUT / "ontop").mkdir(parents=True, exist_ok=True)
    for stale in (OUT / "sql").glob("*.sql"):
        stale.unlink()
    for n, (source, (module, database)) in enumerate(SOURCES.items(), 1):
        (OUT / "sql" / f"{n:02d}-{database}.sql").write_text(seed(module, database), encoding="utf-8")
    for source, (module, database) in SOURCES.items():
        shutil.copyfile(ONTOP / "mappings" / f"{source}.r2rml.ttl", OUT / "ontop" / f"{source}.r2rml.ttl")
        shutil.copyfile(ONTOP / "metadata" / f"{source}-db-metadata.json", OUT / "ontop" / f"{source}-db-metadata.json")
        (OUT / "ontop" / f"{source}.properties").write_text(properties(database), encoding="utf-8")
    for graph in ("links", "fileindex", "labels", "options"):
        shutil.copyfile(DATA / f"{graph}.ttl", OUT / f"{graph}.ttl")


if __name__ == "__main__":
    main()
